import os
import json
import re

def _clean_int(val: any) -> int:
    try:
        s = re.sub(r"[^\d]", "", str(val or "0"))
        return int(s) if s else 0
    except Exception:
        return 0

def generate_personals(config_dir: str, data: dict) -> None:
    content = f'''# config/personals.py (Auto-generated by Setup Wizard)
first_name = {json.dumps(data.get('first_name', ''))}
middle_name = {json.dumps(data.get('middle_name', ''))}
last_name = {json.dumps(data.get('last_name', ''))}

phone_number = {json.dumps(data.get('phone_number', ''))}
current_city = {json.dumps(data.get('current_city', ''))}
street = {json.dumps(data.get('street', ''))}
state = {json.dumps(data.get('state', ''))}
zipcode = {json.dumps(data.get('zipcode', ''))}
country = {json.dumps(data.get('country', ''))}

ethnicity = {json.dumps(data.get('ethnicity', 'Decline'))}
gender = {json.dumps(data.get('gender', 'Decline'))}
disability_status = {json.dumps(data.get('disability_status', 'Decline'))}
veteran_status = {json.dumps(data.get('veteran_status', 'Decline'))}
'''
    with open(os.path.join(config_dir, "personals.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_questions(config_dir: str, data: dict, resume_path: str) -> None:
    content = f'''# config/questions.py (Auto-generated by Setup Wizard)
default_resume_path = {json.dumps(resume_path)}
years_of_experience = {json.dumps(str(data.get('years_of_experience', '0')))}
require_visa = {json.dumps(data.get('require_visa', 'No'))}

website = {json.dumps(data.get('website', ''))}
linkedIn = {json.dumps(data.get('linkedin', ''))}

desired_salary = {_clean_int(data.get('desired_salary', 0))}
us_citizenship = {json.dumps(data.get('us_citizenship', 'Non-citizen seeking work authorization'))}

linkedin_headline = {json.dumps(data.get('headline', ''))}
notice_period = {_clean_int(data.get('notice_period', 0))}
current_ctc = {_clean_int(data.get('current_ctc', 0))}

linkedin_summary = {json.dumps(data.get('summary', ''))}
cover_letter = {json.dumps(data.get('cover_letter', ''))}
recent_employer = {json.dumps(data.get('recent_employer', ''))}
confidence_level = "High"

pause_before_submit = False
pause_at_failed_question = False
overwrite_previous_answers = False
'''
    with open(os.path.join(config_dir, "questions.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_answers(config_dir: str, data: dict) -> None:
    # A generic answers mapping
    content = f'''# config/answers.py (Auto-generated by Setup Wizard)
answers = {{
    "expected salary": {json.dumps(str(data.get('desired_salary', '0')))},
    "require sponsorship": {json.dumps(data.get('require_visa', 'No'))},
    "years of experience": {json.dumps(str(data.get('years_of_experience', '0')))}
}}
'''
    with open(os.path.join(config_dir, "answers.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_custom_questions(config_dir: str, skills_matrix: dict) -> None:
    content = f'''# config/custom_questions.py (Auto-generated by Setup Wizard)
# We export both names for compatibility with different bot versions.
custom_answers = {{
'''
    for skill, years in skills_matrix.items():
        if skill and years is not None:
            content += f'    {json.dumps(skill)}: {json.dumps(str(years))},\n'
    content += "}\n\n"
    
    content += "# Alias for newer router code\n"
    content += "custom_questions = [\n"
    for skill, years in skills_matrix.items():
        if skill and years is not None:
            content += f'    {{"question": {json.dumps(skill)}, "answer": {json.dumps(str(years))}}},\n'
    content += "]\n"
    
    with open(os.path.join(config_dir, "custom_questions.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_all_configs(config_dir: str, data: dict) -> None:
    generate_personals(config_dir, data)
    generate_questions(config_dir, data, data.get("resume_path", ""))
    generate_answers(config_dir, data)
    
    skills_matrix = data.get("skills_matrix", {})
    generate_custom_questions(config_dir, skills_matrix)
