import os

def generate_personals(config_dir: str, data: dict) -> None:
    content = f'''# config/personals.py (Auto-generated by Setup Wizard)
first_name = "{data.get('first_name', '')}"
middle_name = "{data.get('middle_name', '')}"
last_name = "{data.get('last_name', '')}"

phone_number = "{data.get('phone_number', '')}"
current_city = "{data.get('current_city', '')}"
street = "{data.get('street', '')}"
state = "{data.get('state', '')}"
zipcode = "{data.get('zipcode', '')}"
country = "{data.get('country', '')}"

ethnicity = "{data.get('ethnicity', 'Decline')}"
gender = "{data.get('gender', 'Decline')}"
disability_status = "{data.get('disability_status', 'Decline')}"
veteran_status = "{data.get('veteran_status', 'Decline')}"
'''
    with open(os.path.join(config_dir, "personals.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_questions(config_dir: str, data: dict, resume_path: str) -> None:
    content = f'''# config/questions.py (Auto-generated by Setup Wizard)
default_resume_path = "{resume_path}"
years_of_experience = "{data.get('years_of_experience', '0')}"
require_visa = "{data.get('require_visa', 'No')}"

website = "{data.get('website', '')}"
linkedIn = "{data.get('linkedin', '')}"

desired_salary = {int(data.get('desired_salary', 0))}
us_citizenship = "{data.get('us_citizenship', 'Non-citizen seeking work authorization')}"

linkedin_headline = "{data.get('headline', '')}"
notice_period = {int(data.get('notice_period', 0))}
current_ctc = {int(data.get('current_ctc', 0))}

linkedin_summary = """{data.get('summary', '')}"""
cover_letter = """{data.get('cover_letter', '')}"""
recent_employer = "{data.get('recent_employer', '')}"
confidence_level = "High"

pause_before_submit = False
pause_at_failed_question = False
overwrite_previous_answers = False
'''
    with open(os.path.join(config_dir, "questions.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_answers(config_dir: str, data: dict) -> None:
    # A generic answers mapping
    content = f'''# config/answers.py (Auto-generated by Setup Wizard)
answers = {{
    "expected salary": "{data.get('desired_salary', '0')}",
    "require sponsorship": "{data.get('require_visa', 'No')}",
    "years of experience": "{data.get('years_of_experience', '0')}"
}}
'''
    with open(os.path.join(config_dir, "answers.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_custom_questions(config_dir: str, skills_matrix: dict) -> None:
    content = f'''# config/custom_questions.py (Auto-generated by Setup Wizard)
custom_questions = [
'''
    for skill, years in skills_matrix.items():
        if skill and years is not None:
            content += f'    {{"question": "{skill}", "answer": "{years}"}},\n'
    content += "]\n"
    with open(os.path.join(config_dir, "custom_questions.py"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_all_configs(config_dir: str, data: dict) -> None:
    generate_personals(config_dir, data)
    generate_questions(config_dir, data, data.get("resume_path", ""))
    generate_answers(config_dir, data)
    
    skills_matrix = data.get("skills_matrix", {})
    generate_custom_questions(config_dir, skills_matrix)
